### ISSUE TITLE
Bypass Wildcard * does not work

### ISSUE THREAD

**Issue by jasonkhoi** [go-gost/gost#332]
Hi,

I think I have found a bug.

services:
- name: service-0
  addr: ":8080"
  bypass: bypass-0
  handler:
    type: socks5
  listener:
    type: tcp
bypasses:
- name: bypass-0
  whitelist: true
  matchers:
  - '*.example.org'
  - .example.com

This one works: .example.com
subdomain.example.com will result in a match.

But the character * does not work: '*.example.org'
subdomain.example.org will result in NO match.

Can you please check?

Thanks

**Comment by ginuerzh** [comment]
Fixed in nightly version.

**Comment by jasonkhoi** [comment]
Thanks ginuerzh.

I have tested and confirm the wildcard asterisk * nowworks:
subdomain.example.com matches with *.example.com

But it's still not working when wildcard dot . combines with wildcard asterisk:
For example subdomain.example.com is supposed to match with .ex*ple.com but it results in NO match.

Can you please check?

Thanks

**Comment by ginuerzh** [comment]
Currently wildcard `*` cannot be used in combination with dot matcher `.`.

**Comment by jasonkhoi** [comment]
okay thanks @ginuerzh. I will close ticket as you have solved the original issue.
